- hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute a command
      ansible.builtin.shell: "./{{ item }}"
      loop:
        - one.sh
        - two.sh
      async: 60
      poll: 0
      register: loop_status-b

    #- debug:
    #    var: loop_status

    #- name: Execute one
    #  shell: ./one.sh
    #  async: 60
    #  poll: 0
    #  register: one_shell

    #- name: Execute one
    #  shell: ./two.sh
    #  async: 60
    #  poll: 0
    #  register: two_shell

    - name: Wait to finish the commands
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 5
      retries: 20
      loop: "{{ loop_status-b.results }}"
        #- "{{ one_shell }}"
        #- "{{ two_shell }}"
