---
- hosts: all
  connection: local
  tasks:
    - debug:
        var: hostvars

    - debug:
        msg: |
          "{{ hostvars['item'].connection }}"
          "{{ hostvars['item'].token_ocp }}"
      loop: "{{ inventory_hostname }}"
