---
- hosts: all
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - debug:
        msg: |
          "{{ hostvars[item].environment['connection'] }}"
          "{{ hostvars[item].environment['token_ocp'] }}"
      loop: 
        - "{{ inventory_hostname }}"

    - kubernetes.core.k8s:
        host: https://api.cluster-jrgf4.jrgf4.sandbox1307.opentlc.com:6443
        api_key: sha256~4-XfmDHxRZn76T206SLNKHGDZ2LqwM7vyRHZnV2iYAE
        validate_certs: false
        kind: Pod
      register: pod_list

    - debug:
        var: pod_list.stdout_lines
