---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Set a variable for the workflow
      ansible.builtin.set_stats:
        data:
          bola: "jabulani"
      when: node == "first"

    - name: Use the variable from the previous node
      ansible.builtin.debug:
        msg: "The value is {{ bola }}"
      when: node == "second"
