---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create inventory dynamic
      ansible.builtin.add_host:
        name: "{{ item }}.{{ domain }}"
        group: new_hosts
      with_items:
        - "{{ new_hosts }}"

- name: Register New RHEL Servers
  hosts: new_hosts
  vars:
    satellite_url: "https://sat01.jferre.local"
    satellite_org: "JF_LOCAL"
    satellite_user: "jferre"
    satellite_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63623539613564623361393036326138326630306163316135393337326464366535393836373933
          6332616431346437643239363462343833396262636234310a333734343964346630613731623736
          63626661393165313165656134663232313737393961633734323165363333313538643032353864
          3237323139366132330a653735373562336338353738613031383930313161623163663662346331
          3063

  tasks:
  - name: Working on Server
    ansible.builtin.debug:
      msg: "Host: {{ inventory_hostname }} | SO: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
    when: ansible_distribution == 'RedHat'

  - name: Install Katello CA RPM from Satellite
    ansible.builtin.dnf:
      name: "{{ satellite_url }}/pub/katello-ca-consumer-latest.noarch.rpm"
      state: present
      sslverify: false
      validate_certs: false
      disable_gpg_check: true

  - name: Register server on Satellite
    community.general.redhat_subscription:
      state: present
      activationkey: "{{ activation_key }}"
      org_id: "{{ satellite_org }}"
      force_register: true

  - name: Set a hostgroup on new host registered
    redhat.satellite.host:
      username: "{{ satellite_user }}"
      password: "{{ satellite_pass }}"
      server_url: "{{ satellite_url }}"
      name: "{{ inventory_hostname }}"
      organization: "{{ satellite_org }}"
      hostgroup: "JOAO"
      validate_certs: false
