---
- name: Generate memory inventory for host to be registered
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create inventory dynamic
      ansible.builtin.add_host:
        name: "{{ item }}"
        group: new_hosts
      with_items:
        - "{{ hostname }}"
                 
- name: Register New RHEL Servers
  hosts: new_hosts
  connection: local
  vars_files:
    - vault/vault.yml
   
  tasks:
  - name: Working on Server
    ansible.builtin.debug:
      msg: "Host: {{ inventory_hostname }} | SO: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
    when: ansible_distribution == 'RedHat'

  - name: Configuring hostname with FQDN
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
      use: systemd
    ignore_errors: true

  - name: Install Katello CA RPM from Satellite
    ansible.builtin.dnf:
      name: "{{ satellite_url }}/pub/katello-ca-consumer-latest.noarch.rpm"
      state: present
      sslverify: false
      validate_certs: false
      disable_gpg_check: true
                                                 
  - name: Register server on Satellite
    community.general.redhat_subscription:
      state: present
      activationkey: "{{ satellite_ak }}"
      org_id: "{{ satellite_org }}"
      force_register: true
   
  - name: Get the Host ID from Satellite API 
    ansible.builtin.uri:
      url: "{{ satellite_url }}/api/hosts?search=name~{{ inventory_hostname_short }}"
      method: GET
      user: "{{ satellite_user }}"
      password: "{{ satellite_pass }}"
      force_basic_auth: yes
      validate_certs: false
      return_content: yes
    register: host_search_result
    delegate_to: localhost

  - name: Validate if Host was found
    ansible.builtin.fail:
      msg: "ERROR: The host '{{ inventory_hostname }}' was registered but not found at the Satellite API. Verify the latency and the registered host."
    when: host_search_result.json.total == 0
    delegate_to: localhost

  - name: Get the Hostgroup ID to configure on this host
    ansible.builtin.uri:
      url: "{{ satellite_url }}/api/hostgroups?search=name={{ satellite_hostgroup }}"
      method: GET
      user: "{{ satellite_user }}"
      password: "{{ satellite_pass }}"
      force_basic_auth: yes
      validate_certs: false
      return_content: yes
    register: hostgroup_search_result
    delegate_to: localhost

  - name: Validate if Hostgroup exists
    ansible.builtin.fail:
      msg: "Config ERROR: The Hostgroup '{{ satellite_hostgroup }}' does not exist on Satellite. Verify the 'satellite_hostgroup' variable."
    when: hostgroup_search_result.json.total == 0
    delegate_to: localhost

  - name: Update the Host with Hostgroup
    ansible.builtin.uri:
      url: "{{ satellite_url }}/api/hosts/{{ host_search_result.json.results[0].id }}"
      method: PUT
      user: "{{ satellite_user }}"
      password: "{{ satellite_pass }}"
      force_basic_auth: yes
      validate_certs: false
      body_format: json
      body:
        host:
          hostgroup_id: "{{ hostgroup_search_result.json.results[0].id }}"
    delegate_to: localhost
